title = "Vicente Lisboa Portfolio"
baseURL = "https://vicentelisboa.github.io/"
languageCode = "en-us"
theme = "ananke"


#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
#resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Vicente Lisboa"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.es]
    title = "Vicente Lisboa es"
    weight = 2
    contentDir = "content/es"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/vicente-lisboa/"

[[params.ananke_socials]]
name = "GitHub"
url = "https://github.com/vicentelisboa"
